apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 5
  name: cloud-assignment-3-deployment
spec:
  selector:
    matchLabels:
      app: cloud-assignment-3
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-assignment-3
    spec:
      containers:
        - name: container1
          imagePullPolicy: Always
          image: "northamerica-northeast1-docker.pkg.dev/cloud-assignment-3-389918/container1/container1"
          ports:
            - containerPort: 3000
          env:
            - name: "PORT"
              value: "3000"
          volumeMounts:
            - name: cloud-assignment-3-storage
              mountPath: /JEET_PV_dir/data/
        - name: container2
          imagePullPolicy: Always
          image: "northamerica-northeast1-docker.pkg.dev/cloud-assignment-3-389918/container2/container2"
          ports:
            - containerPort: 3001
          env:
            - name: "PORT"
              value: "3001"
          volumeMounts:
            - name: cloud-assignment-3-storage
              mountPath: /JEET_PV_dir/data/
      volumes:
        - name: cloud-assignment-3-storage
          persistentVolumeClaim:
            claimName: cloud-assignment-3-pvc