apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloud-assignment-3-pv
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/JEET_PV_dir"