apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-assignment-3-pvc
spec:
  volumeName: cloud-assignment-3-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi